### ISSUE TITLE
refactor: Card.tsx에 책임을 더 주기

### ISSUE THREAD

**Issue by kkyueing** [OHHAKO/flashcard#13]
`Card.tsx`가 현재는 `title`을 prop으로 가지고 있는데 그 대신 `word`와 `flipped`를 받도록 바꾸면 어떨까요? 지금은 앞면을 보여줄지 뒷면을 보여줄지 여부를 `App.tsx`에서 판단하고 있는데 그 책임을 `Card.tsx`에게 위임하면 좋을 것 같아서요. 괜찮은 것 같으면 PR을 열어보겠습니다.

**Comment by OHHAKO** [comment]
책임 위임 좋은거 같습니다. 근데 이벤트 핸들러는 App.tsx에 있어도 괜찮을까요? #11 에서 Card 작업이 좀 진행됐는데 이벤트 핸들러로 맨 밑의 카드를 컨트롤하고 있어서요.

제가 word, flipped 를 받도록 #11에서 파생된 PR을 열어볼게요. 생각하신 방향과 다르면 클로즈 해주세요.

**Comment by kkyueing** [comment]
수정하신 코드 좋아요 :)

> 근데 이벤트 핸들러는 App.tsx에 있어도 괜찮을까요?

안그래도 `App.tsx`가 좀 긴 것 같아서 줄여보면 좋을 것 같다는 생각을 하고 있었어요. 지금 상태로 조금 더 놔두고 보다가 적당한 계기(?)가 생기면 더 개선해보는걸로 할까요?

이 이슈는 닫을게요. 고생하셨습니다. 👍
