### ISSUE TITLE
feat: 상태 저장하고 불러오기

### ISSUE THREAD

**Issue by kkyueing** [OHHAKO/flashcard#20]
https://github.com/OHHAKO/flashcard/pull/9#discussion_r1501805031 에서 이어지는 이슈입니다. 현재는 상태가 메모리에만 있어서 앱을 종료하면 모두 사라집니다. 상태를 저장하고 불러오는 로직을 추가해야 합니다.

@OHHAKO 님이 전에 사용해보신 라이브러리인 [mmkv](https://github.com/mrousavy/react-native-mmkv)를 써서 구현하기로 했습니다.

**Comment by OHHAKO** [comment]
간단하게 기능 기획을 적어볼게요. 나중에 설정화면 같은게 있어서 초기화, 카드 테마 변경 이런게 있어도 좋겠네요.
- 카드가 나오기 전에 스토리지에서 deck 불러오기
- 카드 아래 버튼을 누를때마다 deck 상태를 스토리지에 갱신하기
- 갱신 실패/성공 상관없이 카드 진행하기 (실패하면 무시)
- 설정화면 같은게
