### ISSUE TITLE
feat: 카드 크기를 키우고 버튼을 아래로 옮기기

### ISSUE THREAD

**Issue by kkyueing** [OHHAKO/flashcard#21]
지금 디자인은 왼쪽처럼 생겼는데 이걸 오른쪽처럼 바꿔보면 어떨까요?

<img width="443" alt="image" src="https://github.com/OHHAKO/flashcard/assets/52947296/dd21e79c-197d-4238-8e80-a4c5f1355577">

제안하는 이유는 이렇습니다:

- 카드를 누를 때랑 버튼을 누를 때 엄지손가락이 최소한으로만 움직이면 좋겠습니다.
- 카드와 버튼이 좀 더 엄지손가락으로 누르기 쉬운 위치(thumbzone)에 있으면 좋겠습니다.

**Comment by OHHAKO** [comment]
작은 카드 디자인이 귀엽지만! 손가락이 불편할 수 있겠네요... UI를 조정해볼게요.
