### ISSUE TITLE
docs: `README.md`에 개발환경 세팅에 대한 내용 넣기

### ISSUE THREAD

**Issue by kkyueing** [OHHAKO/flashcard#7]
`README.md`에 개발환경 세팅에 대한 내용이 담기면 좋겠어요. 일단은 맥, iOS, yarn, VS Code 조합을 쓴다고 가정하고 아래 내용을 담아보면 어떨까요?

- 처음에 1회만 하면 되는 작업
- git pull 받은 후에 해야하는 작업
- 단위 테스트 실행 방법

**Comment by kkyueing** [comment]
우왕 초안 좋아요 :)

참, 저는 CocoaPod 버전이 `1.5.2`인데 `Podfile.lock`의 버전은 `1.5.0`이라서 제 컴퓨터에서 `npx pod-install`을 하면 `Podfile.lock`의 마지막줄이 `COCOAPODS: 1.15.0`에서 `COCOAPODS: 1.15.2`로 변경되더라고요(변경된 `Podfile.lock`은 임시로 커밋하지 않고 있어요).

각 개발자들이 CocoaPod을 패치 버전(major.minor.patch)까지 동일하게 설치하는 게 맞는거겠죠? 이런 내용도 README에 적을까요?

**Comment by OHHAKO** [comment]
오옥 네! cocoapod 버전이 다르면 native 종속성이 다르게 설치되는 문제가 있는데 라이브러리 설치할때 특히 사이드이펙트가 발생할 수 있어요. build에 관여하는 친구들(cocoapod, ruby, jdk, node)은 왠만하면 버전을 맞추는게 좋아요. 이걸 놓쳤네요!
PR 올리고 tool-versions도 추가해볼게유

**Comment by kkyueing** [comment]
오왕 좋아요 :) 고생하셨습니다.
