### ISSUE TITLE
feat: 최근에 봤던 카드는 드물게 보여주기

### ISSUE THREAD

**Issue by kkyueing** [OHHAKO/flashcard#8]
카드 목록에서 어떤 카드를 어떤 순서로 보여줄지 잘 정하는 게 중요할 것 같아요. 일단은 간단하게 아래와 같이 만들고, 단어가 많아지면 좀 더 똑똑한 방식을 도입하면 좋겠습니다.

- 못외운 카드 중 본지 가장 오래된 카드들을 먼저 보여준다.
- 외운 카드는 정해진 시간 안에 다시 보여주지 않는다.
- 한 번 외웠던 카드라도 이후에 사용자가 '못 외웠음'을 고르면 못 외운 카드로 간주한다.

**Comment by kkyueing** [comment]
미리 알고리즘만 만들고 있다가 #4 완료 후에 합쳐볼게요 :)

**Comment by OHHAKO** [comment]
좋은 생각이에요. 저도 순서 기획과 관련된 모델링, 애니메이션을 구상해보고 싶어 질문드려요.
카드 순서를 결정하는 변수는 마지막으로 본 시간, 암기 유무이고 상수는 쿨타임 시간인가요? 값이 모두 같은 카드는 FIFO로 정해지는지도 궁금해요.

**Comment by kkyueing** [comment]
> 좋은 생각이에요. 그럼 [#5](https://github.com/OHHAKO/flashcard/pull/5) 는 이슈없으면 머지시킬게요.

네 :)

> 저도 순서 기획과 관련된 모델링, 애니메이션을 구상해보고 싶어 질문드려요. 카드 순서를 결정하는 변수는 마지막으로 본 시간, 암기 유무이고 상수는 쿨타임 시간인가요? 값이 모두 같은 카드는 FIFO로 정해지는지도 궁금해요.

네, 일단은 마지막으로 본 시간, 암기 유무만으로 정렬 순서가 정해지게 하면 좋겠어요. 아마 우선순위 큐(priority queue)를 쓰면 되겠다 싶어요. 값이 같지 않도록 약간 랜덤값을 더해줘도 좋을 것 같아요([Jittering?](https://en.wikipedia.org/wiki/Jitter)].
